name: Eureka Server Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    uses: personal-blog-project/infra-docker-compose/.github/workflows/service-ci-template.yml@main
    with:
      service_name: eureka-server
